#!/usr/bin/env node
/**
 * judge.mjs -- run the duel against a blind model instead of a person.
 *
 *   ./judge.mjs pairs.json [--votes 3] [--jobs 4] [--out judged.json]
 *   ./judge.mjs pairs.json --trend other.json more.json    (compare bursts)
 *
 * The human scores stopped being comparable to each other. Zach went 33%, 17%,
 * 25%, 25%, 8% while his median decision time halved -- he was learning faster
 * than the generator was improving, so a falling number could mean either
 * thing and there was no way to tell which.
 *
 * A blind judge cannot learn. Every pair is a fresh process with no memory of
 * any other pair, no knowledge of this project, and no idea which system wrote
 * which side. Run the same judge over burst 4 and burst 9 and the difference
 * is the generator, because nothing else changed.
 *
 * It is a WEAKER detector than a human who knows the author -- it has never
 * read the archive and cannot know that Abe says "yay". So read it as a floor,
 * not a ceiling: a burst it cannot crack may still be obvious to Zach, but a
 * burst it cracks easily is not close.
 *
 * The reasons it gives are the point as much as the score. They are the
 * automated version of the notes, and they arrive without anyone having to sit
 * there and play twelve rounds.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

import { callModelAsync } from './redige.mjs';

/** Deliberately spare. It must not know the krewe exists, that one side came
 *  from an archive, or that anybody is trying to make one pass as the other --
 *  every one of those is a hint about what to look for. */
const JUDGE_PROMPT = `You are shown two emails, A and B, sent to the same mailing list.

One was written by a person. The other was generated by an AI given the same
facts. Decide which one the person wrote.

Answer with ONLY this JSON and nothing else:

{"pick": "A" or "B", "confidence": "high" or "low", "why": "one short sentence naming what decided it"}`;

const die = (msg, code = 1) => { console.error(`judge: ${msg}`); process.exit(code); };

/** Stable coin flip per pair per vote, so a rerun of the same file judges the
 *  same layout and two bursts are compared on equal terms. */
function realOnA(pairId, vote) {
  const h = createHash('sha1').update(`${pairId}:${vote}`).digest();
  return (h[0] & 1) === 0;
}

function parse(text) {
  let s = String(text).trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  if (!s.startsWith('{')) {
    const a = s.indexOf('{'), b = s.lastIndexOf('}');
    if (a > -1 && b > a) s = s.slice(a, b + 1);
  }
  const d = JSON.parse(s);
  if (d.pick !== 'A' && d.pick !== 'B') throw new Error(`pick was ${JSON.stringify(d.pick)}`);
  return d;
}

async function judgeOne(pair, vote) {
  const onA = realOnA(pair.id, vote);
  const body = `--- EMAIL A ---\n${onA ? pair.real : pair.ai}\n\n--- EMAIL B ---\n${onA ? pair.ai : pair.real}`;
  const d = parse(await callModelAsync(JUDGE_PROMPT, body));
  const pickedReal = (d.pick === 'A') === onA;
  // `onA` is kept so the run can score what a CONSTANT responder would have got on this
  // exact layout (#22). Without it, position bias is invisible and a judge that always
  // says A reports a fooled-rate that reads like discrimination.
  return { pick: d.pick, pickedReal, onA, confidence: d.confidence, why: String(d.why || '').trim() };
}

/** Two-sided exact binomial p for `k` of `n` at p=0.5, by summing the tail. No
 *  dependency and no approximation: n here is dozens, so exact is cheap and a normal
 *  approximation would be wrong in exactly the small-n case that matters. */
export function twoSidedBinomialP(k, n) {
  if (!n) return 1;
  const hi = Math.max(k, n - k);
  // Factorials in log space, so a few hundred votes cannot overflow.
  const logFact = new Array(n + 1).fill(0);
  for (let i = 1; i <= n; i++) logFact[i] = logFact[i - 1] + Math.log(i);
  let tail = 0;
  for (let i = hi; i <= n; i++) {
    tail += Math.exp(logFact[n] - logFact[i] - logFact[n - i] + n * Math.log(0.5));
  }
  return Math.min(1, 2 * tail);
}

/** A run that did not DISCRIMINATE returns output shaped like one that did (#22).
 *
 *  Burst 11, batched: the judge answered A in ten of twelve rounds and the harness
 *  reported 67% fooled -- 67 points above the same specimens scored per-pair, against an
 *  arc that eleven bursts of real tuning had moved by 8. The twelve rationales were
 *  fluent, specific and drawn from the correct vocabulary, so nothing in the output
 *  distinguished it from a breakthrough. Position bias at 10/12 is p=0.039; the 67% is
 *  p=0.194 against chance. The bias was the only significant effect in the run.
 *
 *  So the split is ALWAYS reported, and past the binomial threshold no rate is emitted at
 *  all -- a number withheld cannot be pasted into an arc table. A figure that is always
 *  printed is a guard; a threshold someone might trip is a rule they edit later. */
export function positionAudit(results) {
  const n = results.length;
  const saidA = results.filter(r => r.pick === 'A').length;
  const p = twoSidedBinomialP(saidA, n);
  // What a responder that ALWAYS said A, or always B, would have scored as "fooled" on
  // this exact layout. On a balanced layout both land near 50%.
  const constA = n ? 100 * results.filter(r => !r.onA).length / n : 0;
  const constB = n ? 100 * results.filter(r => r.onA).length / n : 0;
  return { n, saidA, saidB: n - saidA, p, constA, constB, degenerate: n > 0 && p < 0.05 };
}

async function pool(items, jobs, fn) {
  const out = new Array(items.length).fill(null);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(jobs, items.length) }, async () => {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      try { out[i] = await fn(items[i], i); }
      catch (err) { console.error(`   judge failed: ${String(err.message || err).split('\n')[0]}`); }
    }
  }));
  return out;
}

function arg(args, name, fallback) {
  const i = args.indexOf(name);
  return i === -1 ? fallback : args[i + 1];
}

async function run(path, votes, jobs) {
  const burst = JSON.parse(readFileSync(path, 'utf8'));
  const pairs = (burst.pairs || []).filter(p => p.real && p.ai);
  if (!pairs.length) die(`no pairs in ${path}`, 3);

  const jobsList = [];
  for (const p of pairs) for (let v = 0; v < votes; v++) jobsList.push({ p, v });

  const results = await pool(jobsList, jobs, async ({ p, v }) => ({ id: p.id, ...(await judgeOne(p, v)) }));
  const ok = results.filter(Boolean);

  const byPair = new Map();
  for (const r of ok) {
    if (!byPair.has(r.id)) byPair.set(r.id, []);
    byPair.get(r.id).push(r);
  }
  // A pair counts as caught when a majority of its votes found the real one.
  let caught = 0;
  for (const [, rs] of byPair) {
    if (rs.filter(r => r.pickedReal).length * 2 > rs.length) caught++;
  }
  const fooled = byPair.size - caught;
  // A pair whose every vote errored leaves the rate quietly measured on a
  // smaller denominator. Burst 11 reported 0/10 from a 12-pair file and
  // nothing in the output said which two were missing.
  if (byPair.size < pairs.length) {
    console.error(`   ${pairs.length - byPair.size} of ${pairs.length} pair(s) got no verdict; rate below is on the rest`);
  }
  const audit = positionAudit(ok);
  return { path, pairs: byPair.size, votes: ok.length, caught, fooled, audit,
           // No rate at all when the run did not discriminate (#22). null, not 0 -- a 0
           // would read as "never fooled", which is a finding, and this is the absence of
           // one.
           rate: audit.degenerate || !byPair.size
             ? null : Math.round(100 * fooled / byPair.size),
           results: ok };
}

// CLI only when INVOKED, not when imported. Without this guard a test that imports
// `twoSidedBinomialP` runs the whole command line and exits 2 on the usage check --
// which is how the guard in #22 nearly shipped untested.
if (process.argv[1] && process.argv[1].endsWith('judge.mjs')) {
  const args = process.argv.slice(2);
  if (!args.length || args.includes('--help')) {
    console.error('usage: judge.mjs pairs.json [--votes 3] [--jobs 4] [--out FILE]');
    console.error('       judge.mjs a.json b.json c.json --trend');
    process.exit(2);
  }

  const votes = Number(arg(args, '--votes', 3));
  const jobs = Number(arg(args, '--jobs', 4));
  const out = arg(args, '--out', null);
  const files = args.filter(a => !a.startsWith('--') && a.endsWith('.json') && a !== out);

  const all = [];
  for (const f of files) {
    const r = await run(f, votes, jobs);
    all.push(r);
    const a = r.audit;
    const split = `said A ${a.saidA}/${a.n}`;
    if (r.rate === null && a.degenerate) {
      // The whole point: no percentage on this line, so nothing can be copied out of it.
      console.log(`${f.split('/').pop().padEnd(16)} DEGENERATE -- ${split} (two-sided p=${a.p.toFixed(3)}). `
        + `No fooled-rate emitted: this run did not discriminate, so any rate would describe `
        + `position bias. A constant "A" scores ${a.constA.toFixed(0)}% fooled on this layout.`);
    } else {
      console.log(`${f.split('/').pop().padEnd(16)} fooled the judge on ${r.fooled}/${r.pairs}  (${r.rate}%)   `
        + `${r.votes} votes   ${split}, p=${a.p.toFixed(2)}, constant-A would score ${a.constA.toFixed(0)}%`);
    }
  }

  if (all.length > 1) {
    console.log('\ntrend, blind judge, 50% is indistinguishable:');
    for (const r of all) {
      // A degenerate run is not plotted. Giving it a bar would put it on the arc, which is
      // the exact mistake #22 records -- 67% read as the breakthrough eleven bursts had been
      // waiting for.
      if (r.rate === null) {
        console.log(`  ${r.path.split('/').pop().padEnd(16)}    - |${'DEGENERATE, not plotted'.padEnd(50, ' ')}|`);
        continue;
      }
      const bar = '#'.repeat(Math.round(r.rate / 2)).padEnd(50, '.');
      console.log(`  ${r.path.split('/').pop().padEnd(16)} ${String(r.rate + '%').padStart(4)} |${bar}|`);
    }
  }

  // The reasons are the automated version of a human's notes, and the whole
  // point of running this unattended.
  const last = all[all.length - 1];
  const caughtWhy = last.results.filter(r => r.pickedReal).map(r => r.why).filter(Boolean);
  if (caughtWhy.length) {
    console.log(`\nwhat gave it away, ${last.path.split('/').pop()}:`);
    for (const w of caughtWhy.slice(0, 14)) console.log(`  - ${w}`);
  }

  if (out) {
    writeFileSync(out, JSON.stringify(all, null, 2));
    console.log(`\n-- wrote ${out}`);
  }
}
