#!/usr/bin/env node
/**
 * judge.mjs -- run the duel against a blind model instead of a person.
 *
 *   ./judge.mjs pairs.json [--votes 3] [--jobs 4] [--out judged.json]
 *   ./judge.mjs pairs.json --trend other.json more.json    (compare bursts)
 *
 * The human scores stopped being comparable to each other. Zach went 33%, 17%,
 * 25%, 25%, 8% while his median decision time halved -- he was learning faster
 * than the generator was improving, so a falling number could mean either
 * thing and there was no way to tell which.
 *
 * A blind judge cannot learn. Every pair is a fresh process with no memory of
 * any other pair, no knowledge of this project, and no idea which system wrote
 * which side. Run the same judge over burst 4 and burst 9 and the difference
 * is the generator, because nothing else changed.
 *
 * It is a WEAKER detector than a human who knows the author -- it has never
 * read the archive and cannot know that Abe says "yay". So read it as a floor,
 * not a ceiling: a burst it cannot crack may still be obvious to Zach, but a
 * burst it cracks easily is not close.
 *
 * The reasons it gives are the point as much as the score. They are the
 * automated version of the notes, and they arrive without anyone having to sit
 * there and play twelve rounds.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

import { callModelAsync } from './redige.mjs';

/** Deliberately spare. It must not know the krewe exists, that one side came
 *  from an archive, or that anybody is trying to make one pass as the other --
 *  every one of those is a hint about what to look for. */
const JUDGE_PROMPT = `You are shown two emails, A and B, sent to the same mailing list.

One was written by a person. The other was generated by an AI given the same
facts. Decide which one the person wrote.

Answer with ONLY this JSON and nothing else:

{"pick": "A" or "B", "confidence": "high" or "low", "why": "one short sentence naming what decided it"}`;

const die = (msg, code = 1) => { console.error(`judge: ${msg}`); process.exit(code); };

/** Stable coin flip per pair per vote, so a rerun of the same file judges the
 *  same layout and two bursts are compared on equal terms. */
function realOnA(pairId, vote) {
  const h = createHash('sha1').update(`${pairId}:${vote}`).digest();
  return (h[0] & 1) === 0;
}

function parse(text) {
  let s = String(text).trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  if (!s.startsWith('{')) {
    const a = s.indexOf('{'), b = s.lastIndexOf('}');
    if (a > -1 && b > a) s = s.slice(a, b + 1);
  }
  const d = JSON.parse(s);
  if (d.pick !== 'A' && d.pick !== 'B') throw new Error(`pick was ${JSON.stringify(d.pick)}`);
  return d;
}

async function judgeOne(pair, vote) {
  const onA = realOnA(pair.id, vote);
  const body = `--- EMAIL A ---\n${onA ? pair.real : pair.ai}\n\n--- EMAIL B ---\n${onA ? pair.ai : pair.real}`;
  const d = parse(await callModelAsync(JUDGE_PROMPT, body));
  const pickedReal = (d.pick === 'A') === onA;
  return { pick: d.pick, pickedReal, confidence: d.confidence, why: String(d.why || '').trim() };
}

async function pool(items, jobs, fn) {
  const out = new Array(items.length).fill(null);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(jobs, items.length) }, async () => {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      try { out[i] = await fn(items[i], i); }
      catch (err) { console.error(`   judge failed: ${String(err.message || err).split('\n')[0]}`); }
    }
  }));
  return out;
}

function arg(args, name, fallback) {
  const i = args.indexOf(name);
  return i === -1 ? fallback : args[i + 1];
}

async function run(path, votes, jobs) {
  const burst = JSON.parse(readFileSync(path, 'utf8'));
  const pairs = (burst.pairs || []).filter(p => p.real && p.ai);
  if (!pairs.length) die(`no pairs in ${path}`, 3);

  const jobsList = [];
  for (const p of pairs) for (let v = 0; v < votes; v++) jobsList.push({ p, v });

  const results = await pool(jobsList, jobs, async ({ p, v }) => ({ id: p.id, ...(await judgeOne(p, v)) }));
  const ok = results.filter(Boolean);

  const byPair = new Map();
  for (const r of ok) {
    if (!byPair.has(r.id)) byPair.set(r.id, []);
    byPair.get(r.id).push(r);
  }
  // A pair counts as caught when a majority of its votes found the real one.
  let caught = 0;
  for (const [, rs] of byPair) {
    if (rs.filter(r => r.pickedReal).length * 2 > rs.length) caught++;
  }
  const fooled = byPair.size - caught;
  return { path, pairs: byPair.size, votes: ok.length, caught, fooled,
           rate: byPair.size ? Math.round(100 * fooled / byPair.size) : 0, results: ok };
}

const args = process.argv.slice(2);
if (!args.length || args.includes('--help')) {
  console.error('usage: judge.mjs pairs.json [--votes 3] [--jobs 4] [--out FILE]');
  console.error('       judge.mjs a.json b.json c.json --trend');
  process.exit(2);
}

const votes = Number(arg(args, '--votes', 3));
const jobs = Number(arg(args, '--jobs', 4));
const out = arg(args, '--out', null);
const files = args.filter(a => !a.startsWith('--') && a.endsWith('.json') && a !== out);

const all = [];
for (const f of files) {
  const r = await run(f, votes, jobs);
  all.push(r);
  console.log(`${f.split('/').pop().padEnd(16)} fooled the judge on ${r.fooled}/${r.pairs}  (${r.rate}%)   ${r.votes} votes`);
}

if (all.length > 1) {
  console.log('\ntrend, blind judge, 50% is indistinguishable:');
  for (const r of all) {
    const bar = '#'.repeat(Math.round(r.rate / 2)).padEnd(50, '.');
    console.log(`  ${r.path.split('/').pop().padEnd(16)} ${String(r.rate + '%').padStart(4)} |${bar}|`);
  }
}

// The reasons are the automated version of a human's notes, and the whole
// point of running this unattended.
const last = all[all.length - 1];
const caughtWhy = last.results.filter(r => r.pickedReal).map(r => r.why).filter(Boolean);
if (caughtWhy.length) {
  console.log(`\nwhat gave it away, ${last.path.split('/').pop()}:`);
  for (const w of caughtWhy.slice(0, 14)) console.log(`  - ${w}`);
}

if (out) {
  writeFileSync(out, JSON.stringify(all, null, 2));
  console.log(`\n-- wrote ${out}`);
}
